name: Tweet
on:
  schedule:
    - cron: "0 4 * * *"
    - cron: "0 7 * * *"
    - cron: "0 10 * * *"
    - cron: "0 13 * * *"
    - cron: "0 16 * * *"
    - cron: "0 19 * * *"
    - cron: "0 22 * * *"
  push:
    branches:
      - master

jobs:
  pytest:
    name: Tweet Covid19 Info
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
      - name: envirnment setting
        run: |
          pip install poetry==1.0.2
          poetry install
      - name: Run main script
        run: |
          poetry run python src/main.py
