name: Tweet
on:
  schedule:
    - cron: "*/5 * * * *"
  push:
    branches:
      - master

jobs:
  tweet:
    name: Tweet Covid19 Info
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Run main script
        run: |
          deno run --allow-net --allow-read --allow-write --allow-env  src/main.ts
        env:
          webhook_access_key: ${{ secrets.webhook_access_key }}
      - name: Commit a Cache
        shell: bash
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add --all
          git diff-index --quiet HEAD || git commit -m 'Save Latest Tweet'
          git pull
          git push
