name: Tweet
on:
  # schedule:
  # - cron: "*/10 * * * *"
  push:
    branches:
      - master

jobs:
  pytest:
    name: Tweet Covid19 Info
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Get current time
        uses: gerred/actions/current-time@master
        id: current-time
      - name: Cache Message File
        uses: actions/cache@v1
        with:
          path: .cache
          key: msg-cache-${{ runner.os }}-${{ steps.current-time.outputs.time  }}
          restore-keys: msg-cache-${{ runner.os }}
      - name: Set Up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
      - name: envirnment setting
        run: |
          pip install poetry==1.0.2
          poetry install --no-dev
      - name: Run main script
        run: |
          poetry run python src/main.py
        env:
          webhook_access_key: ${{ secrets.webhook_access_key }}
