name: Tweet
on:
  schedule:
    - cron: "*/10 * * * *"
  push:
    branches:
      - master

jobs:
  pytest:
    name: Tweet Covid19 Info
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Cache node_modules
        uses: actions/cache@preview
        with:
          path: .cache
          key: msg-cache-${{ runner.os }}
          restore-keys: msg-cache-${{ runner.os }}
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
      - name: envirnment setting
        run: |
          pip install poetry==1.0.2
          poetry install
      - name: Run main script
        run: |
          poetry run python src/main.py
        env:
          webhook_access_key: ${{ secrets.webhook_access_key }}
